version: '2'
services: 
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      SPARK_HOME: /opt/spark
      MASTER: "spark://master:7077"
    ports:
      - 8090:8090
    volumes:
      - zeppelin:/opt/zeppelin
      - opt:/opt/spark
    restart: unless-stopped

volumes:
  zeppelin:
    external: true
  opt:
    external: true
